accounts/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', views.user_login, name='login'),
    path('register/', views.user_register, name='register'),
    path('logout/', views.userlogout, name='logout'),
    path('dashboard/', views.Dashboard.as_view(), name='dashboard'),
    path('changepassword/', auth_views.PasswordChangeView.as_view(template_name='accounts/change_password.html', success_url='/account/dashboard/'), name='changepassword'),
    path('success/<str:info>/', views.Success.as_view(), name='success'),
    path('updateprofile/<slug:slug>/', views.ProfileUpdateView.as_view(), name='updateprofile'),
    path('deleteaccount/<slug:slug>/', views.DeleteUserView.as_view(), name='deleteaccount'),
    path('addbankaccount/', views.add_bank_details, name='add_bank_details'),
    path('admin/<slug:username>/<slug:action>/', views.approve_or_block_user_view, name='approve_or_block'),
    path('admin/blockedusers/', views.BlockUsers.as_view(), name='blocked_users'),
    path('admin/manageartisans/', views.ManageArtisansView.as_view(), name='manage_artisans'),
    path('admin/managecustomers/', views.ManageCustomersView.as_view(), name='manage_customers'),
    path('admindeleteuser/<slug:slug>/', views.AdminDeleteUserView.as_view(), name='admin_deleteaccount'),
    path('social/completeprofile/', views.CompleteProfile.as_view(), name='social_complete_profile'),
    path('withdrawals/', views.WithdrawListView.as_view(), name='withdrawal_list_view')
]

accounts/templates/accounts/add_bank_details.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% load static %}
{% load accounts_tag %}
{% block title %}
    Add your bank details
{% endblock title %}

{% block body %}
<div class="row">
    <div class="col-4 text-center">
        <div class="row">
            <div class="col-md-1"></div>
            <div class="col-md-10">
                {% if user.userprofile.photo %}
                <img src="{{MEDIA_URL}}/{{user.userprofile.photo}}" class="img-fluid img-thumbnail rounded-circle"
                    alt="{{user.first_name}}">
                {% else %}
                    {% if user.userprofile.gender == "male" or user.is_staff%}
                    <img src="{% static "images/male.jpg" %}" class="img-fluid img-thumbnail rounded-circle"
                        alt="{{user.first_name}}">
                    {% else %}
                    <img src="{% static "images/female.jpg" %}" class="img-fluid img-thumbnail rounded-circle"
                        alt="{{user.first_name}}">
                    {% endif %}
                {% endif %}
            </div>
            <div class="col-md-1"></div>
        </div>
        {% if user.is_staff %}
            <h4 class="form_text">{{user.first_name.title}} {{user.last_name.title}}</h4>
            <i class="fas fa-user-tag form_text my-2"></i> <strong>{{user.username}}</strong><br />
            <span class="form_text my-1"><strong>Joined:</strong></span> <strong>{{user.date_joined}}</strong><br />
        {% else %}
            {% if user.userprofile.user_type == "artisan" %}
                <h4 class="form_text">{{user.first_name.title}} {{user.last_name.title}}</h4>
                <div class="card-text my-2">
                    {% for service in user.userprofile.services|splitter %}
                    <span class="badge bg-primary mb-1" style="font-size: 0.9rem;">{{service.title}}</span>
                    {% endfor %}
                </div>
                <span class="form_text my-1"><strong>Joined:</strong></span> <strong>{{user.date_joined}}</strong><br />
                <i class="fas fa-user-tag form_text my-2"></i> <strong>{{user.username}}</strong><br />
                <i class="far fa-calendar-alt form_text my-2"></i> <strong>{{user.userprofile.age}} years old</strong><br />
                <i class="fas fa-venus-mars form_text my-2"></i> <strong>{{user.userprofile.gender.title}}</strong><br />
                <i class="fas fa-map-marker-alt form_text my-2"></i> <strong>{{user.userprofile.city.title}}, UK</strong>
                <h5><i class="fas fa-pound-sign form_text my-2"></i><strong>{{user.userprofile.price}}Flat rate</strong></h5>
                <div class="star my-2">
                    {% if user.userprofile.get_rating >= 1 %}
                    <i class="fas fa-star"></i>
                    {% elif user.userprofile.get_rating >= 0.5 %}
                    <i class="fas fa-star-half-alt"></i>
                    {% else %}
                    <i class="far fa-star"></i>
                    {% endif %}
                
                    {% if user.userprofile.get_rating >= 2 %}
                    <i class="fas fa-star"></i>
                    {% elif user.userprofile.get_rating >= 1.5 %}
                    <i class="fas fa-star-half-alt"></i>
                    {% else %}
                    <i class="far fa-star"></i>
                    {% endif %}
                
                    {% if user.userprofile.get_rating >= 3 %}
                    <i class="fas fa-star"></i>
                    {% elif user.userprofile.get_rating >= 2.5 %}
                    <i class="fas fa-star-half-alt"></i>
                    {% else %}
                    <i class="far fa-star"></i>
                    {% endif %}
                
                    {% if user.userprofile.get_rating >= 4 %}
                    <i class="fas fa-star"></i>
                    {% elif user.userprofile.get_rating >= 3.5 %}
                    <i class="fas fa-star-half-alt"></i>
                    {% else %}
                    <i class="far fa-star"></i>
                    {% endif %}
                
                    {% if user.userprofile.get_rating >= 5 %}
                    <i class="fas fa-star"></i>
                    {% elif user.userprofile.get_rating >= 4.5 %}
                    <i class="fas fa-star-half-alt"></i>
                    {% else %}
                    <i class="far fa-star"></i>
                    {% endif %}
                    </div>
                <strong>
                {% if user.userprofile.get_total_reviews > 0 %}
                    {{user.userprofile.get_total_reviews}} review{{ user.userprofile.get_total_reviews|pluralize }}
                {% else %}
                    You don't have reviews yet
                {% endif %}
                </strong>
            {% else %}
                
            {% endif %}
        {% endif %}
    </div>
    <div class="col-8">
        <div class="row">
            <div class="col-md-2"></div>
            <div class="col-md-8 form_text">
                <h3 class="blue text-center"><strong>Add your bank details</strong></h3>
                <form method="post">
                    {% csrf_token %}
                    <div class="form-floating mb-3">
                        <input type="text"  name="bank_name" value="{{bank_name}}" class="form-control" id="floatingInput" placeholder="Bank Name">
                        <label for="floatingInput">Bank Name</label>
                    </div>
                    <div class="row g-2">
                        <div class="col-md">
                            <div class="form-floating">
                                <input type="text" name="sort_code" class="form-control" id="floatingInputGrid" placeholder="Sort Code"
                                    value="{{sort_code}}" minlength="6" maxlength="6" onkeypress="return (event.charCode !==8 && event.charCode ===0 || (event.charCode >= 48 && event.charCode <= 57))">
                                <label for="floatingInputGrid">Sort Code</label>
                            </div>
                        </div>
                        <div class="col-md">
                            <div class="form-floating">
                                <input type="text" name="account_number" class="form-control" id="floatingInputGrid" placeholder="Account Number"
                                    value="{{account_number}}" minlength="8" maxlength="8" onkeypress="return (event.charCode !==8 && event.charCode ===0 || (event.charCode >= 48 && event.charCode <= 57))">
                                <label for="floatingInputGrid">Account Number</label>
                            </div>
                        </div>
                    </div>
                    {% if error %}
                        <div class="alert alert-danger alert-dismissible fade show mt-2 text-center" role="alert">
                            {{error}}
                            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                        </div>
                    {% endif %}
                    <div class="d-grid gap-2 mt-2">
                        <button class="btn btn-primary" type="submit"><strong>ADD BANK DETAILS</strong></button>
                    </div>
                </form>
            </div>
            <div class="col-md-2"></div>
        </div>
    </div>
</div>
<br> {% endblock body %}

accounts/templates/accounts/blocked_users.html
{% extends 'base.html' %} 
{% load django_bootstrap5 %} 
{% load static %} 
{% load accounts_tag %} 
{% block title %}
    Blocked users
{% endblock title %}


{% block body %}
<div class="row">
    <div class="col-4 text-center">
        <div class="row">
            <div class="col-md-1"></div>
            <div class="col-md-10">
                {% if user.userprofile.photo %}
                <img src="{{MEDIA_URL}}/{{user.userprofile.photo}}" class="img-fluid img-thumbnail rounded-circle" alt="{{user.first_name}}"> {% else %} {% if user.userprofile.gender == "male" or user.is_staff%}
                <img src="{% static "images/male.jpg " %}" class="img-fluid img-thumbnail rounded-circle" alt="{{user.first_name}}"> {% else %}
                <img src="{% static "images/female.jpg " %}" class="img-fluid img-thumbnail rounded-circle" alt="{{user.first_name}}"> {% endif %} {% endif %}
            </div>
            <div class="col-md-1"></div>
        </div>
        {% if user.is_staff %}
            <h5><span class="badge bg-success">ADMIN</span></h5>
        {% else %} 
        {% if user.userprofile.user_type == "artisan" %}
            <h5><span class="badge bg-primary">ARTISAN</span></h5>
        {% else %}
            <h5><span class="badge bg-info">CUSTOMER</span></h5>
        {% endif %} 
        {% endif %} 
        {% if user.is_staff %}
        <h4 class="form_text">{{user.first_name.title}} {{user.last_name.title}}</h4>
        <i class="fas fa-user-tag form_text my-2"></i> <strong>{{user.username}}</strong><br />
        <span class="form_text my-1"><strong>Joined:</strong></span> <strong>{{user.date_joined}}</strong><br /> {% else %} {% if user.userprofile.user_type == "artisan" %}
        <h4 class="form_text">{{user.first_name.title}} {{user.last_name.title}}</h4>
        <div class="card-text my-2">
            {% for service in user.userprofile.services|splitter %}
            <span class="badge bg-primary" style="font-size: 0.9rem;">{{service.title}}</span> {% endfor %}
        </div>
        <span class="form_text my-1"><strong>Joined:</strong></span> <strong>{{user.date_joined}}</strong><br />
        <i class="fas fa-user-tag form_text my-2"></i> <strong>{{user.username}}</strong><br />
        <i class="far fa-calendar-alt form_text my-2"></i> <strong>{{user.userprofile.age}} years old</strong><br />
        <i class="fas fa-venus-mars form_text my-2"></i> <strong>{{user.userprofile.gender.title}}</strong><br />
        <i class="fas fa-map-marker-alt form_text my-2"></i> <strong>{{user.userprofile.city.title}}, UK</strong>
        <h5><i class="fas fa-pound-sign form_text my-2"></i><strong>{{user.userprofile.price}} Flat rate</strong></h5>
        <div class="star my-2">
            {% if user.userprofile.get_rating >= 1 %}
            <i class="fas fa-star"></i> {% elif user.userprofile.get_rating >= 0.5 %}
            <i class="fas fa-star-half-alt"></i> {% else %}
            <i class="far fa-star"></i> {% endif %} {% if user.userprofile.get_rating >= 2 %}
            <i class="fas fa-star"></i> {% elif user.userprofile.get_rating >= 1.5 %}
            <i class="fas fa-star-half-alt"></i> {% else %}
            <i class="far fa-star"></i> {% endif %} {% if user.userprofile.get_rating >= 3 %}
            <i class="fas fa-star"></i> {% elif user.userprofile.get_rating >= 2.5 %}
            <i class="fas fa-star-half-alt"></i> {% else %}
            <i class="far fa-star"></i> {% endif %} {% if user.userprofile.get_rating >= 4 %}
            <i class="fas fa-star"></i> {% elif user.userprofile.get_rating >= 3.5 %}
            <i class="fas fa-star-half-alt"></i> {% else %}
            <i class="far fa-star"></i> {% endif %} {% if user.userprofile.get_rating >= 5 %}
            <i class="fas fa-star"></i> {% elif user.userprofile.get_rating >= 4.5 %}
            <i class="fas fa-star-half-alt"></i> {% else %}
            <i class="far fa-star"></i> {% endif %}
        </div>
        <strong>
                {% if user.userprofile.get_total_reviews > 0 %}
                    {{user.userprofile.get_total_reviews}} review{{ user.userprofile.get_total_reviews|pluralize }}
                {% else %}
                    You don't have reviews yet
                {% endif %}
                </strong> {% else %} {% endif %} {% endif %}
    </div>
    <div class="col-8">
        {% if blocked_artisans.count > 0 %}
            <h4>There are <span class="form_text">{{blocked_artisans.count}}</span> blocked users.</h4>
            {% for artisan in blocked_artisans %}
                <div class="card p-3 my-3">
                    <div class="row">
                        <h4 style="color: red;">BLOCKED</h4>
                        <div class="col">
                            <strong class="form_text" style="font-size: 1.3rem;">{{artisan.user.first_name.title}} {{artisan.user.last_name.title}}</strong>
                        </div>
                        <div class="col">
                            <i class="fas fa-pound-sign form_text"></i><strong style="color: black;">{{artisan.price}} Flat rate</strong>
                        </div>
                        <div class="col">
                            <i class="fas fa-map-marker-alt form_text"></i> <strong style="color: black;">{{artisan.city.title}}, UK</strong>
                        </div>
                    </div>
                    <div class="card-text my-2 skills">
                        {% for service in artisan.services|splitter %}
                            <span class="badge bg-primary" style="font-size: 0.75rem;">{{service.title}}</span>
                        {% endfor %}
                    </div>
                    <div class="row">
                        <div class="col-md-6 d-grid gap-2">
                            <a class="btn btn-success" href="{% url 'accounts:approve_or_block' username=artisan.user.username action="approve" %}"><strong><i class="fas fa-thumbs-up"></i> UNBLOCK AND APPROVE</strong></a>
                        </div>
                        <div class="col-md-6 d-grid gap-2">
                            <a class="btn btn-warning" href="{% url 'accounts:approve_or_block' username=artisan.user.username action="unblock" %}"><strong><i class="fas fa-ban"></i> UNBLOCK</strong></a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        {% else %}
            <h4 class="text-center form_text my-6">There is no blocked user to display.</h4>
        {% endif %}
       
    </div>
</div>
<br> {% endblock body %}

accounts/templates/accounts/change_password_done.html
{% extends 'base.html' %} {% load django_bootstrap5 %} {% load static %} {% load accounts_tag %} {% block body %}
<div class="row">
    <div class="col-4 text-center">
        <div class="row">
            <div class="col-md-1"></div>
            <div class="col-md-10">
                {% if user.userprofile.photo %}
                <img src="{{MEDIA_URL}}/{{user.userprofile.photo}}" class="img-fluid img-thumbnail rounded-circle"
                    alt="{{user.first_name}}"> {% else %} {% if user.userprofile.gender == "male" or user.is_staff%}
                <img src="{% static " images/male.jpg " %}" class="img-fluid img-thumbnail rounded-circle"
                    alt="{{user.first_name}}"> {% else %}
                <img src="{% static " images/female.jpg " %}" class="img-fluid img-thumbnail rounded-circle"
                    alt="{{user.first_name}}"> {% endif %} {% endif %}
            </div>
            <div class="col-md-1"></div>
        </div>
        {% if user.is_staff %}
        <h5><span class="badge bg-success">ADMIN</span></h5>
        {% else %} {% if user.userprofile.user_type == "artisan" %}
        <h5><span class="badge bg-primary">ARTISAN</span></h5>
        {% else %}
        <h5><span class="badge bg-info">CUSTOMER</span></h5>
        {% endif %} {% endif %} {% if user.is_staff %}
        <h4 class="form_text">{{user.first_name.title}} {{user.last_name.title}}</h4>
        <i class="fas fa-user-tag form_text my-2"></i> <strong>{{user.username}}</strong><br />
        <span class="form_text my-1"><strong>Joined:</strong></span> <strong>{{user.date_joined}}</strong><br /> {% else
        %} {% if user.userprofile.user_type == "artisan" %}
        <h4 class="form_text">{{user.first_name.title}} {{user.last_name.title}}</h4>
        <div class="card-text my-2">
            {% for service in user.userprofile.services|splitter %}
            <span class="badge bg-primary" style="font-size: 0.9rem;">{{service.title}}</span> {% endfor %}
        </div>
        <span class="form_text my-1"><strong>Joined:</strong></span> <strong>{{user.date_joined}}</strong><br />
        <i class="fas fa-user-tag form_text my-2"></i> <strong>{{user.username}}</strong><br />
        <i class="far fa-calendar-alt form_text my-2"></i> <strong>{{user.userprofile.age}} years old</strong><br />
        <i class="fas fa-venus-mars form_text my-2"></i> <strong>{{user.userprofile.gender.title}}</strong><br />
        <i class="fas fa-map-marker-alt form_text my-2"></i> <strong>{{user.userprofile.city.title}}, UK</strong>
        <h5><i class="fas fa-pound-sign form_text my-2"></i><strong>{{user.userprofile.price}}/hr</strong></h5>
        <div class="star my-2">
            {% if user.userprofile.get_rating >= 1 %}
            <i class="fas fa-star"></i> {% elif user.userprofile.get_rating >= 0.5 %}
            <i class="fas fa-star-half-alt"></i> {% else %}
            <i class="far fa-star"></i> {% endif %} {% if user.userprofile.get_rating >= 2 %}
            <i class="fas fa-star"></i> {% elif user.userprofile.get_rating >= 1.5 %}
            <i class="fas fa-star-half-alt"></i> {% else %}
            <i class="far fa-star"></i> {% endif %} {% if user.userprofile.get_rating >= 3 %}
            <i class="fas fa-star"></i> {% elif user.userprofile.get_rating >= 2.5 %}
            <i class="fas fa-star-half-alt"></i> {% else %}
            <i class="far fa-star"></i> {% endif %} {% if user.userprofile.get_rating >= 4 %}
            <i class="fas fa-star"></i> {% elif user.userprofile.get_rating >= 3.5 %}
            <i class="fas fa-star-half-alt"></i> {% else %}
            <i class="far fa-star"></i> {% endif %} {% if user.userprofile.get_rating >= 5 %}
            <i class="fas fa-star"></i> {% elif user.userprofile.get_rating >= 4.5 %}
            <i class="fas fa-star-half-alt"></i> {% else %}
            <i class="far fa-star"></i> {% endif %}
        </div>
        <strong>
            {% if user.userprofile.get_total_reviews > 0 %}
            {{user.userprofile.get_total_reviews}} review{{ user.userprofile.get_total_reviews|pluralize }}
            {% else %}
            You don't have reviews yet
            {% endif %}
        </strong> {% else %} {% endif %} {% endif %}
    </div>
    <div class="col-8 info_div">
        <div class="col-10 col-md-8 col-lg-6 blue text-center">
            <h1><i class="far fa-check-circle fa-3x"></i></h1>
            <h5>Your password change was successful</h5>
            <a href="{% url 'accounts:dashboard' %}"><button class="btn btn-outline-primary btn-lg">Go to Dashboard</button></a>
        </div>
    </div>
</div>
<br> {% endblock body %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% load static %}
{% block title %}
    Login
{% endblock title %}

{% block body %}
<script src="https://www.google.com/recaptcha/api.js"></script>
<script src="https://www.google.com/recaptcha/api.js?render=6LcfPh8bAAAAACbRBFFMW05cAtZ6ybRzMSaSQKvI"></script>
<script>
    function onSubmit(token) {
      document.getElementById("form").submit();
    }
</script>
<script>
    function onClick(e) {
      e.preventDefault();
      grecaptcha.ready(function() {
        grecaptcha.execute('6LcfPh8bAAAAACbRBFFMW05cAtZ6ybRzMSaSQKvI', {action: 'submit'}).then(function(token) {
            // Add your logic to submit to your backend server here.
        });
      });
    }
</script>
<div class="row justify-content-center">
    <div class="col-10 col-md-8 col-lg-6 form_text text-center">
        <h3 class="blue"><strong>Sign in to your account</strong></h3>
        {% if error %}
            <div class="alert alert-danger alert-dismissible fade show" role="alert">
                {{error}}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        {% endif %}
        <form action="" method="post">
            {% csrf_token %}
            {% bootstrap_form form layout="floating" %}
            <input type="hidden" name="next" value="{{ request.GET.next }}" />
            <div class="d-grid gap-2">
                <button class="btn btn-primary" type="submit"><strong>SIGN IN</strong></button>
            </div>
        </form>



        <div class="d-grid gap-2 mt-2">
            <a class="btn btn-outline-dark" href="/external/google/login/?process=login" role="button" style="text-transform:none">
                <img width="20px" style="margin-bottom:3px; margin-right:5px" alt="Google sign-in" src="https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Google_%22G%22_Logo.svg/512px-Google_%22G%22_Logo.svg.png" />
                <strong>Sign in with Google</strong>
              </a>
        </div>
        <p><em>Don't have an account yet?</em> <a href="{% url 'accounts:register' %}" style="text-decoration: none;">

                <span class="links" class="g-recaptcha" 
                data-sitekey="reCAPTCHA_site_key" 
                data-callback='onSubmit' 
                data-action='submit'><Strong>REGISTER</Strong></span>
            </a><br>
            <a href="{% url 'password_reset' %}" class="links" style="text-decoration: none;"><strong>Forgot password or
                    username?</strong></span></a>
        </p>

        <br>
        This site is protected by reCAPTCHA and the Google
        <a href="https://policies.google.com/privacy">Privacy Policy</a> and
        <a href="https://policies.google.com/terms">Terms of Service</a> apply.
    </div>
</div>
{% endblock body %}

accounts/templates/accounts/manage_artisans.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% load static %}
{% load accounts_tag %}
{% block title %}
    Manage Artisans 
{% endblock title %}

{% block body %}
<div class="row">
    <div class="col-4 text-center">
        <div class="row">
            <div class="col-md-1"></div>
            <div class="col-md-10">
                <img src="{% static "images/male.jpg" %}" class="img-fluid img-thumbnail rounded-circle"
                    alt="{{user.first_name}}">
            </div>
            <div class="col-md-1"></div>
        </div>
            <h4 class="form_text">{{user.first_name.title}} {{user.last_name.title}}</h4>
            <i class="fas fa-user-tag form_text my-2"></i> <strong>{{user.username}}</strong><br />
            <span class="form_text my-1"><strong>Joined:</strong></span> <strong>{{user.date_joined}}</strong><br />
    </div>
    <div class="col-8">
        {% if artisans.count > 0 %}
        <h4>There are <span class="form_text">{{artisans.count}}</span> Artisans registered on the site</h4>
        
            {% for artisan in artisans %}
                <div class="card p-3 my-3">
                    <div class="row">
                        <div class="col">
                            <strong class="form_text" style="font-size: 1.3rem;">{{artisan.user.first_name.title}} {{artisan.user.last_name.title}}</strong>
                        </div>
                        <div class="col">
                            <i class="fas fa-pound-sign form_text"></i><strong style="color: black;">{{artisan.price}}Flat rate</strong>
                        </div>
                        <div class="col">
                            <i class="fas fa-map-marker-alt form_text"></i> <strong style="color: black;">{{artisan.city.title}}, UK</strong>
                        </div>
                    </div>
                    <div class="card-text my-2 skills">
                        {% for service in artisan.services|splitter %}
                            <span class="badge bg-primary" style="font-size: 0.75rem;">{{service.title}}</span>
                        {% endfor %}
                    </div>
                    <div class="row">
                        <div class="col-md-6 d-grid gap-2">
                            <a class="btn btn-success" href="{% url 'user-detail' user_type=artisan.user_type slug=artisan.user.username %}"><strong><i class="fas fa-eye"></i> VIEW {{artisan.user.first_name.upper}}'s PROFILE</strong></a>
                        </div>
                        <div class="col-md-6 d-grid gap-2">
                            <a class="btn btn-danger" href="{% url 'accounts:approve_or_block' username=artisan.user.username action="block" %}"><strong><i class="fas fa-ban"></i> BLOCK {{artisan.user.first_name.upper}}</strong></a>
                        </div>
                    </div>
                </div>
            {% endfor %}
            
        {% else %}
        <h4 class="text-center form_text my-6">No Artisan has registered on the site</h4>

        {% endif %}   

    </div>
</div>
<br>
{% endblock body %}

accounts/templates/accounts/registration_successful.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% load static %}
{% block title %}
    Registration Successfull
{% endblock title %}


{% block body %}
<br>
<br>
<br>
<div class="row justify-content-center">
    <div class="col-10 col-md-8 col-lg-6 blue text-center">
        <h1><i class="far fa-check-circle fa-3x"></i></h1>
        <h4>You're welcome {{info.title}}</h4>
        <h5>Your account has been created successfully</h5>
        <a href="{% url 'accounts:dasboard' %}"><button class="btn btn-outline-primary btn-lg">GO BACK TO MY PROFILE</button></a>
    </div>
</div>
{% endblock body %}

accounts/templates/accounts/social_dashboard.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% load static %}
{% load accounts_tag %}
{% block title %}
    Your Dashboard
{% endblock title %}

{% block body %}
<div class="row">
    <div class="col-4 text-center">
        <div class="row">
            <div class="col-md-1"></div>
            <div class="col-md-10">
                <img src="{{image}}" class="img-fluid img-thumbnail rounded-circle"
                    alt="{{user.first_name}}" width="300" height="300">
            </div>
            <div class="col-md-1"></div>
        </div>
        <h4 class="form_text">{{user.first_name.title}} {{user.last_name.title}}</h4>
        <span class="form_text my-1"><strong>Joined:</strong></span> <strong>{{user.date_joined}}</strong><br />
        <i class="fas fa-user-tag form_text my-2"></i> <strong>{{user.username}}</strong><br />
    </div>
    <div class="col-8">
        <div class="alert alert-warning text-center" role="alert">
            <span class="mb-5"><strong>Completing your profile will give you full access to the site.</strong></span> <br />
            <a href="{% url 'accounts:social_complete_profile' %}"><button class="btn btn-warning"><strong>COMPLETE PROFILE</strong></button></a>
        </div>
    </div>
</div>
<br>
{% endblock body %}