accounts/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', views.user_login, name='login'),
    path('register/', views.user_register, name='register'),
    path('logout/', views.userlogout, name='logout'),
    path('dashboard/', views.Dashboard.as_view(), name='dashboard'),
    path('changepassword/', auth_views.PasswordChangeView.as_view(template_name='accounts/change_password.html', success_url='/account/dashboard/'), name='changepassword'),
    path('success/<str:info>/', views.Success.as_view(), name='success'),
    path('updateprofile/<slug:slug>/', views.ProfileUpdateView.as_view(), name='updateprofile'),
    path('deleteaccount/<slug:slug>/', views.DeleteUserView.as_view(), name='deleteaccount'),
    path('addbankaccount/', views.add_bank_details, name='add_bank_details'),
    path('admin/<slug:username>/<slug:action>/', views.approve_or_block_user_view, name='approve_or_block'),
    path('admin/blockedusers/', views.BlockUsers.as_view(), name='blocked_users'),
    path('admin/manageartisans/', views.ManageArtisansView.as_view(), name='manage_artisans'),
    path('admin/managecustomers/', views.ManageCustomersView.as_view(), name='manage_customers'),
    path('admindeleteuser/<slug:slug>/', views.AdminDeleteUserView.as_view(), name='admin_deleteaccount'),
    path('social/completeprofile/', views.CompleteProfile.as_view(), name='social_complete_profile'),
    path('withdrawals/', views.WithdrawListView.as_view(), name='withdrawal_list_view')
]

artim/artim/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import HomePage, redirect_to_home, UserDetailView, goodbye
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path(
        'password-reset/',
        auth_views.PasswordResetView.as_view(
            template_name='password_reset_form.html',
            subject_template_name='password_reset_subject.txt',
            email_template_name='password_reset_email.html'
            ),
        name='password_reset',
    ),
    path(
        'password-reset-done/',
        auth_views.PasswordResetDoneView.as_view(template_name='password_reset_done.html'),
        name='password_reset_done'
    ),
    path(
        'password-reset-confirm/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(template_name='password_reset_confirm.html'),
        name='password_reset_confirm'
    ),
    path(
        'password-reset-complete/',
        auth_views.PasswordResetCompleteView.as_view(template_name='password_reset_complete.html'),
        name='password_reset_complete'
    ),
    path('', redirect_to_home),
    path('<slug>/', HomePage.as_view(), name='index'),
    path('account/', include('accounts.urls')),
    path('order/', include('order.urls')),
    path('profile/<str:user_type>/<slug:slug>/', UserDetailView.as_view(), name='user-detail'),
    path('user/goodbye/', goodbye, name='goodbye'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

artim/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import UserDetailView, goodbye
from django.contrib.auth import views as auth_views
from .views import ArtisanListView, homepage, AlternativeArtisanView
from accounts.views import SocialDashboard

urlpatterns = [
    path('admin/', admin.site.urls),
    path(
        'password-reset/',
        auth_views.PasswordResetView.as_view(
            template_name='password_reset_form.html',
            subject_template_name='password_reset_subject.txt',
            email_template_name='password_reset_email.html'
            ),
        name='password_reset',
    ),
    path(
        'password-reset-done/',
        auth_views.PasswordResetDoneView.as_view(template_name='password_reset_done.html'),
        name='password_reset_done'
    ),
    path(
        'password-reset-confirm/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(template_name='password_reset_confirm.html'),
        name='password_reset_confirm'
    ),
    path(
        'password-reset-complete/',
        auth_views.PasswordResetCompleteView.as_view(template_name='password_reset_complete.html'),
        name='password_reset_complete'
    ),
    path('', homepage, name='homepage'),
    path('<slug>/', ArtisanListView.as_view(), name='index'),
    path('<str:searched>/check/<slug:slug>/', AlternativeArtisanView.as_view(), name='alternative'),
    path('account/', include('accounts.urls')),
    path('order/', include('order.urls')),
    path('profile/<str:user_type>/<slug:slug>/', UserDetailView.as_view(), name='user-detail'),
    path('user/goodbye/', goodbye, name='goodbye'),
    path('accounts/profile/', SocialDashboard.as_view(), name='social_dashboard'),
    path('external/', include('allauth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="google-signin-client_id" content="YOUR_CLIENT_ID.apps.googleusercontent.com">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" />
    <link rel="stylesheet" href="{% static "/css/master.css" %}">
    <title>
        {% block title %}

        {% endblock title %}
    </title>
    <link rel="shortcut icon" type="image/jpg" href="{% static "/images/favicon.png" %}"/>
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-lg sticky-top navbar-light base" style="background-color: white;">
            <div class="container">
                <a class="navbar-brand" href="{% url 'homepage' %}"><strong><span class="blue">ARTIM<span></strong></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="{% url 'index' "home" %}"><strong><span class="blue">Browse
                                        Artisans</span></strong></a>
                        </li>
                    </ul>
                    <ul class="navbar-nav mb-2 mb-lg-0">

                        {% if user.is_authenticated %}
                            {% if user.userprofile or user.is_staff %}
                                <div class="nav-item dropdown drop form_text">
                                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown"
                                        aria-expanded="false">
                                        <i class="fas fa-user-circle fa-1x form_text"></i><span class="form_text" style="font-size: 1.2rem;"> {{user.first_name.title}} {% if user.is_staff %}
                                        <span class="badge bg-success">Admin</span>
                                        {% else %}
                                        {% if user.userprofile.user_type == "artisan" %}
                                        <span class="badge bg-primary">Artisan</span>
                                        {% else %}
                                        <span class="badge bg-info">Customer</span>
                                        {% endif %}
                                        {% endif %}</span>
                                    </a>
                                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                        <li><a class="dropdown-item" href="{% url 'accounts:dashboard' %}"><i class="fas fa-id-card"></i> Your Dashboard</a>
                                        </li>
                                        <li>
                                            <hr class="dropdown-divider">
                                        </li>
                                        {% if user.is_staff %}
                                            <li><a class="dropdown-item" href="{% url 'accounts:manage_artisans' %}"><i class="fas fa-users-cog"></i> Manage Artisans</a></li>
                                            <li><a class="dropdown-item" href="{% url 'accounts:manage_customers' %}"><i class="fas fa-users"></i> Manage Customers</a></li>
                                            <li><a class="dropdown-item" href="{% url 'accounts:blocked_users' %}"><i class="fas fa-ban"></i> Blocked Users</a></li>
                                            <li><a class="dropdown-item" href="{% url 'accounts:changepassword' %}"><i class="fas fa-cogs"></i> Change
                                                    Password</a></li>
                                        {% else %}
                                            <li><a class="dropdown-item" href="{% url 'accounts:updateprofile' slug=user.userprofile.slug %}">
                                                <i class="fas fa-sliders-h"></i> Edit Profile</a></li>
                                            {% if user.userprofile.user_type == 'artisan' %}
                                                <li><a class="dropdown-item" href="{% url 'accounts:withdrawal_list_view'%}">
                                                    <i class="far fa-share-square"></i> My Withdrawals</a></li>
                                            {% endif %}
                                            {% if user.userprofile.bank_details%}
                                                <li><a class="dropdown-item" href="#"><i class="fas fa-university"></i> Edit Bank details</a></li>
                                            {% endif %}
                                                <li><a class="dropdown-item" href="{% url 'accounts:changepassword' %}"><i class="fas fa-cogs"></i> Change
                                                        Password</a></li>
                                                <li><a class="dropdown-item" href="{% url 'accounts:deleteaccount' slug=user.userprofile.slug %}"><i class="fas fa-trash"></i> Delete My Account</a></li>
                                        {% endif %}   
                                    </ul>
                                </div>
                            {% else %}
                                <div class="nav-item dropdown drop form_text">
                                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown"
                                        aria-expanded="false">
                                        <i class="fas fa-user-circle fa-1x form_text"></i><span class="form_text" style="font-size: 1.2rem;"> {{user.first_name.title}}
                                        </span>
                                    </a>
                                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                        <li><a class="dropdown-item" href="{% url 'social_dashboard' %}"><i class="fas fa-id-card"></i> Your Dashboard</a>
                                        </li>
                                        <li>
                                            <hr class="dropdown-divider">
                                        </li>
                                        <li><a class="dropdown-item" href="#"><i class="fas fa-cogs"></i> Change
                                                Password</a></li>
                                        <li><a class="dropdown-item" href="#"><i class="fas fa-trash"></i> Delete My Account</a></li>  
                                    </ul>
                                </div>
                            {% endif %}
                            <li class="nav-item">
                                <a class="nav-link" aria-current="page" href="{% url 'accounts:logout' %}">
                                    <button class="btn btn-outline-primary"><strong><i class="fas fa-power-off"></i> Sign Out</strong></button>
                                </a>
                            </li>
                        {% else %}
                            <li class="nav-item">
                                <a class="nav-link" aria-current="page" href="{% url 'accounts:login' %}">
                                    <button class="btn btn-outline-primary"><strong>Sign In</strong></button>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" aria-current="page" href="{% url 'accounts:register' %}">
                                    <button class="btn btn-outline-primary"><strong>Register</strong></button>
                                </a>
                            </li>
                        {% endif %}

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <main class="container">
        <br />
        {% include 'artim/messages.html' %}
        {% block body %}
        {% endblock body %}
    </main>
    <footer class="mu-3 mb-1">
        <div class="container text-center blue">
            <strong>Copyright &copy; Artim</strong><br />
            <strong>Developed for 7047CEM by Group 1</strong>
        </div>
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous">
    </script>
    <script>
        var tooltipTriggerList = [].slice.call(document.querySelectorAll('[data-bs-toggle="tooltip"]'))
        var tooltipList = tooltipTriggerList.map(function (tooltipTriggerEl) {
        return new bootstrap.Tooltip(tooltipTriggerEl)
        })

    </script>
</body>

</html>

templates/index.html
{% extends 'base.html' %}
{% load static %}
{% load accounts_tag %}

{% block title %}Home{% endblock title %}

{% block body %}
<div class="container">
    <div class="dropdown text-center">
        <a class="btn btn-outline-primary btn-lg dropdown-toggle form_text" href="#" role="button" id="dropdownMenuLink" data-bs-toggle="dropdown"
            aria-expanded="false">
            Filter artisans by a skill
        </a>
        <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
            <li><a class="dropdown-item" href="{% url 'index' "all" %}">All</a></li>
            {% for skill in skills %}
                <li><a class="dropdown-item" href="{% url 'index' skill.0 %}">{{skill.0}}</a></li>
            {% endfor %}
        </ul>
    </div>
    {% if alternative %}
        <div class="alert alert-primary alert-dismissible fade show my-3" role="alert">
            <strong>OOPS!</strong> We tried to search for <strong>{{searched}}</strong> but we couldn't find an Artisan with such skills. Did you mean to type <strong>{{job}}</strong>?
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    {% endif %}
    {% if artisans.count > 0 %}
    <div class="row">
        {% for artisan in artisans %}
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3 col-xl-3 my-3">
            <a href="{% url 'user-detail' user_type=artisan.user_type slug=artisan.user.username %}" style="text-decoration: none;" class="blue"><div class="card fluid" >
                {% if artisan.photo %}
                <img src="{{MEDIA_URL}}/{{artisan.photo}}" class="card-img-top  img-fluid img-thumbnail" alt="{{artisan.user.first_name}}" width="100%" height="2">
                {% else %}
                {% if artisan.gender == "male" %}
                <img src="{% static "images/male.jpg" %}" class="card-img-top img-fluid img-thumbnail" alt="{{artisan.user.first_name}}" width="100%" height="autp">
                {% else %}
                <img src="{% static "images/female.jpg" %}" class="card-img-top img-fluid img-thumbnail" alt="{{artisan.user.first_name}}">
                {% endif %}
                {% endif %}
                <div class="card-body">
                    <h4 class="card-title"><strong></strong>{{artisan.user.first_name.title}}</strong></h4>
                    <div class="card-text my-2 skills">
                        {% for service in artisan.services|splitter %}
                            <span class="badge bg-primary" style="font-size: 0.75rem;">{{service.title}}</span>
                        {% endfor %}
                    </div>
                    <h5><i class="fas fa-pound-sign form_text"></i><strong style="color: black;">{{artisan.price}} Flat rate</strong></h5>
                    <div class="star">
                        {% if artisan.get_rating >= 1 %}
                            <i class="fas fa-star"></i>
                        {% elif artisan.get_rating >= 0.5 %}
                            <i class="fas fa-star-half-alt"></i>
                        {% else %}
                            <i class="far fa-star"></i>
                        {% endif %}

                        {% if artisan.get_rating >= 2 %}
                        <i class="fas fa-star"></i>
                        {% elif artisan.get_rating >= 1.5 %}
                        <i class="fas fa-star-half-alt"></i>
                        {% else %}
                        <i class="far fa-star"></i>
                        {% endif %}

                        {% if artisan.get_rating >= 3 %}
                        <i class="fas fa-star"></i>
                        {% elif artisan.get_rating >= 2.5 %}
                        <i class="fas fa-star-half-alt"></i>
                        {% else %}
                        <i class="far fa-star"></i>
                        {% endif %}

                        {% if artisan.get_rating >= 4 %}
                        <i class="fas fa-star"></i>
                        {% elif artisan.get_rating >= 3.5 %}
                        <i class="fas fa-star-half-alt"></i>
                        {% else %}
                        <i class="far fa-star"></i>
                        {% endif %}

                        {% if artisan.get_rating >= 5 %}
                        <i class="fas fa-star"></i>
                        {% elif artisan.get_rating >= 4.5 %}
                        <i class="fas fa-star-half-alt"></i>
                        {% else %}
                        <i class="far fa-star"></i>
                        {% endif %}
                    </div>
                    <strong style="color: black;">{{artisan.get_total_reviews}} review{{ artisan.get_total_reviews|pluralize }}</strong><br />
                    <div class="my-2"><i class="fas fa-map-marker-alt form_text"></i> <strong style="color: black;">{{artisan.city.title}}, UK</strong></div>
                    <div class="row my-2">
                        <div class="col-5"><i class="far fa-calendar-alt form_text"></i> <strong style="color: black;">{{artisan.age}}</strong></div>
                        <div class="col-7"><i class="fas fa-venus-mars form_text"></i> <strong style="color: black;">{{artisan.gender.title}}</strong></div>
                    </div>
                </div>
            </div>
            </a>
        </div>
        {% endfor %}
    </div>
    <br />
    <br />
    <nav>
        <ul class="pagination pagination pg-success justify-content-center">
            {% if page_obj.has_previous %}
                <li class="page-item"><a class="page-link" href="?page=1">First</a></li>
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a>
                </li>
            {% endif %}
            {% if page_obj.number == 1 %}
                <li class="page-item disabled">
                    <span class="page-link">Previous</span>
                </li>
            {% endif %}
                <li class="page-item active">
                    <span class="page-link">
                        {{ page_obj.number }}
                    <span class="sr-only">(current)</span>
                    </span>
                </li>
            {% if page_obj.has_next %}
                <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a>
                <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">Last</a></li>
            {% endif %}
            {% if page_obj.number == page_obj.paginator.num_pages %}
                <li class="page-item disabled">
                    <span class="page-link">Next</span>
                </li>
            {% endif %}
    
    
        </ul>
    </nav>
    {% else %}
    <br><br>
    <div class="my-10">
        <h4 class="text-center blue">There are no Artisans to be shown.</h4>
    </div>
    {% endif %}
</div>
<br />
{% endblock body %}

templates/password_reset_done.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% load static %}

{% block body %}
<br>
<br>
<br>
<div class="row justify-content-center">
    <div class="col-10 col-md-8 col-lg-6 blue text-center">
        <h1><i class="far fa-check-circle fa-3x"></i></h1>
        <h4>Your password has been reset</h4>
        <h5>Check your email and follow the instructions.</h5>
    </div>
</div>
{% endblock body %}